"""empty message

Revision ID: 14d1ee3f8c92
Revises: 0314010d9e8c
Create Date: 2018-06-08 17:52:09.088275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d1ee3f8c92'
down_revision = '0314010d9e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    op.drop_column('t_user', 'role_id')
    # ### end Alembic commands ###
