"""empty message

Revision ID: b01c962a2b94
Revises: d1c70914df7d
Create Date: 2018-06-07 15:28:51.096750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01c962a2b94'
down_revision = 'd1c70914df7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_1', sa.String(length=200), nullable=True))
    op.add_column('t_user', sa.Column('photo_2', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_2')
    op.drop_column('t_user', 'photo_1')
    # ### end Alembic commands ###
